# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 01:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FN011',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prj_date0', models.DateField(help_text='Start Date')),
                ('prj_date1', models.DateField(help_text='End Date')),
                ('prj_cd', models.CharField(help_text='Project Code', max_length=12, unique=True)),
                ('year', models.CharField(blank=True, editable=False, help_text='Year', max_length=4)),
                ('prj_nm', models.CharField(help_text='Project Name', max_length=60)),
                ('prj_ldr', models.CharField(help_text='Project Lead', max_length=40)),
                ('comment0', models.TextField(help_text='General Project Description.')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('aru', models.TextField(blank=True, null=True)),
                ('fof_loc', models.TextField(blank=True, null=True)),
                ('fof_nm', models.TextField(blank=True, null=True)),
                ('wby', models.TextField(blank=True, null=True)),
                ('wby_nm', models.TextField(blank=True, null=True)),
                ('prj_his', models.TextField(blank=True, null=True)),
                ('prj_size', models.TextField(blank=True, null=True)),
                ('prj_ver', models.TextField(blank=True, null=True)),
                ('v0', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Creel List',
                'ordering': ['-prj_date1'],
            },
        ),
        migrations.CreateModel(
            name='FN022',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn', models.CharField(help_text='Season Code', max_length=2)),
                ('ssn_des', models.CharField(help_text='Season Description', max_length=60)),
                ('ssn_date0', models.DateField(help_text='Season Start Date')),
                ('ssn_date1', models.DateField(help_text='Season End Date')),
                ('v0', models.CharField(max_length=4)),
                ('creel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creel_portal.FN011')),
            ],
            options={
                'verbose_name': 'Seasons',
                'ordering': ['ssn'],
            },
        ),
        migrations.CreateModel(
            name='FN023',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtp', models.CharField(help_text='Day Type Code', max_length=2)),
                ('dtp_nm', models.CharField(help_text='Day Type Name', max_length=10)),
                ('dow_lst', models.CharField(help_text='Day Of Week List', max_length=7)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creel_portal.FN022')),
            ],
            options={
                'verbose_name': 'Day Types',
                'ordering': ['dtp'],
            },
        ),
        migrations.CreateModel(
            name='FN024',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prd', models.CharField(help_text='Day Type Code', max_length=2)),
                ('prdtm0', models.TimeField(help_text='Period Start Time')),
                ('prdtm1', models.TimeField(help_text='Period End Time')),
                ('daytype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creel_portal.FN023')),
            ],
            options={
                'verbose_name': 'Periods',
                'ordering': ['prd'],
            },
        ),
        migrations.CreateModel(
            name='FN025',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Exception Date')),
                ('dtp1', models.CharField(help_text='Day Type Code', max_length=2)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creel_portal.FN022')),
            ],
            options={
                'verbose_name': 'Exception Dates',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='FN026',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space', models.CharField(help_text='Space Code', max_length=2)),
                ('space_des', models.CharField(help_text='Space Description', max_length=100)),
                ('space_siz', models.IntegerField(blank=True, null=True)),
                ('area_cnt', models.IntegerField(blank=True, null=True)),
                ('area_lst', models.CharField(blank=True, help_text='Area List', max_length=2, null=True)),
                ('area_wt', models.FloatField(blank=True, null=True)),
                ('ddlat', models.FloatField(blank=True, null=True)),
                ('creel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creel_portal.FN011')),
            ],
            options={
                'verbose_name': 'Spatial Strata',
                'ordering': ['space'],
            },
        ),
        migrations.CreateModel(
            name='FN028',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(help_text='Mode Code', max_length=2)),
                ('mode_des', models.CharField(help_text='Fishing Mode Description', max_length=100)),
                ('atyunit', models.IntegerField(help_text='Activity Unit')),
                ('itvunit', models.IntegerField(help_text='Interview Unit')),
                ('chkflag', models.IntegerField(help_text='Check Flag')),
                ('creel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creel_portal.FN011')),
            ],
            options={
                'verbose_name': 'Fishing Mode',
                'ordering': ['mode'],
            },
        ),
        migrations.CreateModel(
            name='FN111',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sama', models.CharField(max_length=6)),
                ('date', models.DateField()),
                ('samtm0', models.TimeField(help_text='Interview Period Start')),
                ('weather', models.CharField(max_length=200)),
                ('comment1', models.CharField(help_text='Comments about current interview period.', max_length=200)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creel_portal.FN026')),
                ('creel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creel_portal.FN011')),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creel_portal.FN028')),
            ],
            options={
                'verbose_name': 'Inveriew Log',
                'ordering': ['creel', 'sama'],
            },
        ),
        migrations.CreateModel(
            name='Lake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbrev', models.CharField(max_length=10, unique=True)),
                ('lake_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Lake',
            },
        ),
        migrations.AddField(
            model_name='fn011',
            name='lake',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='creel_portal.Lake'),
        ),
        migrations.AlterUniqueTogether(
            name='fn111',
            unique_together=set([('creel', 'sama')]),
        ),
        migrations.AlterUniqueTogether(
            name='fn028',
            unique_together=set([('creel', 'mode')]),
        ),
        migrations.AlterUniqueTogether(
            name='fn026',
            unique_together=set([('creel', 'space')]),
        ),
        migrations.AlterUniqueTogether(
            name='fn024',
            unique_together=set([('daytype', 'prd')]),
        ),
        migrations.AlterUniqueTogether(
            name='fn023',
            unique_together=set([('season', 'dtp')]),
        ),
        migrations.AlterUniqueTogether(
            name='fn022',
            unique_together=set([('creel', 'ssn')]),
        ),
    ]
