# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creel_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FN121',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sam', models.CharField(max_length=6)),
                ('itvseq', models.IntegerField()),
                ('itvtm0', models.TimeField(help_text='Interview Time')),
                ('date', models.DateField()),
                ('efftm0', models.TimeField(help_text='Fishing Start Time')),
                ('efftm1', models.TimeField(blank=True, help_text='Fishing End Time', null=True)),
                ('effcmp', models.BooleanField(default=False)),
                ('effdur', models.FloatField(blank=True, null=True)),
                ('persons', models.IntegerField(blank=True, null=True)),
                ('anglers', models.IntegerField(blank=True, null=True)),
                ('rods', models.IntegerField(blank=True, null=True)),
                ('angmeth', models.IntegerField(blank=True, null=True)),
                ('angvis', models.IntegerField(blank=True, null=True)),
                ('angorig', models.IntegerField(blank=True, null=True)),
                ('angop1', models.IntegerField(blank=True, null=True)),
                ('angop2', models.IntegerField(blank=True, null=True)),
                ('angop3', models.IntegerField(blank=True, null=True)),
                ('comment1', models.TextField(null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creel_portal.FN026')),
                ('creel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creel_portal.FN011')),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creel_portal.FN028')),
                ('sama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creel_portal.FN111')),
            ],
            options={
                'verbose_name': 'Inveriew',
                'ordering': ['creel', 'sam'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='fn121',
            unique_together=set([('creel', 'sam')]),
        ),
    ]
