# Generated by Django 2.2.7 on 2020-04-09 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creel_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fn025',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='fn023',
            name='dtp',
            field=models.CharField(choices=[(1, 'weekday'), (2, 'weekend')], db_index=True, help_text='Day Type Code', max_length=2),
        ),
        migrations.AlterField(
            model_name='fr712',
            name='stratum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strata_attributes', to='creel_portal.Strata'),
        ),
    ]
