# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creel_portal', '0002_auto_20170425_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fr711',
            name='strat_comb',
            field=models.CharField(default='++_++_++_++', max_length=11),
        ),
    ]
