# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creel_portal', '0002_auto_20170210_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='FN123',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sek', models.BooleanField(default=True)),
                ('hvscnt', models.IntegerField(default=0)),
                ('rlscnt', models.IntegerField(default=0)),
                ('mescnt', models.IntegerField(default=0)),
                ('meswt', models.FloatField(blank=True, null=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creel_portal.FN121')),
            ],
            options={
                'ordering': ['interview', 'species'],
                'verbose_name': 'Catch',
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_code', models.IntegerField(unique=True)),
                ('common_name', models.CharField(max_length=30)),
                ('scientific_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['species_code'],
            },
        ),
        migrations.AddField(
            model_name='fn123',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creel_portal.Species'),
        ),
        migrations.AlterUniqueTogether(
            name='fn123',
            unique_together=set([('interview', 'species')]),
        ),
    ]
