# Generated by Django 2.2.7 on 2020-04-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creel_portal', '0002_auto_20200409_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fn025',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='fn025',
            unique_together={('season', 'date')},
        ),
    ]
