# Generated by Django 2.2.12 on 2020-06-06 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creel_portal', '0004_auto_20200415_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fn011',
            name='field_crew',
            field=models.ManyToManyField(related_name='creel_crew', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fn123',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Species'),
        ),
    ]
