# Generated by Django 2.2.7 on 2021-11-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creel_portal', '0006_auto_20200606_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='fn127',
            name='ageaDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fn127',
            name='agest',
            field=models.CharField(blank=True, db_index=True, max_length=5, null=True, verbose_name='Age Structure'),
        ),
        migrations.AddField(
            model_name='fn127',
            name='comment7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fn127',
            name='preferred',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Preferred age estimate for a fish'),
        ),
        migrations.AddField(
            model_name='fn127',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fn127',
            name='agea',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Age Assessed (yr)'),
        ),
        migrations.AlterField(
            model_name='fn127',
            name='agemt',
            field=models.CharField(max_length=6, verbose_name='Age Method Data'),
        ),
        migrations.AlterField(
            model_name='fn127',
            name='conf',
            field=models.IntegerField(blank=True, null=True, verbose_name='Confidence'),
        ),
        migrations.AlterField(
            model_name='fn127',
            name='edge',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Edge Code'),
        ),
        migrations.AlterField(
            model_name='fn127',
            name='nca',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Complete Annuli'),
        ),
    ]
