# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creel_portal', '0006_strata_period'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fn111',
            options={'ordering': ['creel__prj_cd', 'sama'], 'verbose_name': 'Inveriew Log'},
        ),
        migrations.AddField(
            model_name='fn111',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='interview_logs', to='creel_portal.FN026'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fn111',
            name='creel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='interview_logs', to='creel_portal.FN011'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fn111',
            name='daycode',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fn111',
            name='mode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='interview_logs', to='creel_portal.FN028'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='fn111',
            unique_together=set([('creel', 'sama')]),
        ),
    ]
