# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creel_portal', '0007_auto_20170425_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fn111',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='fn111',
            name='daycode',
            field=models.CharField(db_index=True, max_length=1),
        ),
    ]
