# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creel_portal', '0008_auto_20170425_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='fn111',
            name='daytype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='interview_logs', to='creel_portal.FN023'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fn111',
            name='period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='interview_logs', to='creel_portal.FN024'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fn111',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='interview_logs', to='creel_portal.FN022'),
            preserve_default=False,
        ),
    ]
