# Generated by Django 2.2.7 on 2021-11-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creel_portal', '0008_populate_fn127_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fn127',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
