# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-27 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creel_portal', '0009_auto_20170425_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fn121',
            options={'ordering': ['sama__creel__prj_cd', 'sam'], 'verbose_name': 'Inveriew'},
        ),
        migrations.AlterModelOptions(
            name='fr713',
            options={'ordering': ['stratum__creel_run__creel__prj_cd', 'run', 'stratum__stratum_label', 'date', 'rec_tp'], 'verbose_name': 'EffortEstimate'},
        ),
        migrations.AlterModelOptions(
            name='fr714',
            options={'ordering': ['stratum__creel_run__creel__prj_cd', 'stratum__creel_run__run', 'stratum__stratum_label', 'species', 'date', 'rec_tp', 'sek'], 'verbose_name': 'HarvestEstimate'},
        ),
        migrations.AddField(
            model_name='fn121',
            name='angop4',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='fn121',
            name='angop5',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='fn121',
            name='angop1',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='fn121',
            name='angop2',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='fn121',
            name='angop3',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='fr711',
            name='creel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creel_run', to='creel_portal.FN011'),
        ),
        migrations.AlterField(
            model_name='fr711',
            name='fr71_est',
            field=models.IntegerField(choices=[(1, '1-stage'), (2, '2-stage')]),
        ),
        migrations.AlterField(
            model_name='fr711',
            name='fr71_unit',
            field=models.IntegerField(choices=[(0, 'Rods'), (1, 'Anglers'), (2, 'Parties')]),
        ),
    ]
