# Generated by Django 2.2.7 on 2021-11-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creel_portal', '0009_fn127_slug_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='fn126',
            name='fdmes',
            field=models.CharField(blank=True, choices=[(None, 'No Data'), ('L', 'Length'), ('W', 'Weight'), ('V', 'Volume')], help_text='Food Measure Code', max_length=2),
        ),
        migrations.AddField(
            model_name='fn126',
            name='foodval',
            field=models.FloatField(blank=True, null=True, verbose_name='Food Measure Value'),
        ),
        migrations.AddField(
            model_name='fn126',
            name='lf',
            field=models.CharField(blank=True, choices=[(None, 'No Data'), ('10', '10'), ('20', '20'), ('30', '30'), ('40', '40'), ('50', '50'), ('60', '60')], help_text='Life Stage', max_length=2),
        ),
        migrations.AlterField(
            model_name='fn126',
            name='foodcnt',
            field=models.IntegerField(blank=True, null=True, verbose_name='Food Count'),
        ),
        migrations.AlterField(
            model_name='fn126',
            name='taxon',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, verbose_name='A taxonomic code used to identify the type of food item.'),
        ),
    ]
