# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creel_portal', '0010_auto_20170427_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fn121',
            name='angop4',
        ),
        migrations.RemoveField(
            model_name='fn121',
            name='angop5',
        ),
        migrations.AddField(
            model_name='fn024',
            name='prd_dur',
            field=models.FloatField(default=0, help_text='Period Duration (hrs)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fn025',
            name='description',
            field=models.CharField(default='Holiday', help_text='Description', max_length=50),
        ),
    ]
