# Generated by Django 2.2.18 on 2022-01-27 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creel_portal', '0011_prune_FN011_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fn022',
            name='v0',
        ),
    ]
