# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creel_portal', '0011_auto_20170428_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='FR712',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_tp', models.IntegerField(choices=[(1, 'creel log (daily)'), (2, 'stratum'), (3, 'multi-stratum')], default=2)),
                ('strat_days', models.IntegerField()),
                ('strat_hours', models.FloatField()),
                ('sam_days', models.IntegerField(blank=True, default=0, null=True)),
                ('sam_hours', models.FloatField(blank=True, default=0, null=True)),
                ('fpc', models.FloatField(default=0)),
                ('prd_dur', models.FloatField()),
                ('atyunit', models.IntegerField(blank=True, choices=[(1, 'Person'), (2, 'Party')], default=2, null=True)),
                ('chkflag', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], default=True, null=True)),
                ('strat1', models.CharField(blank=True, max_length=11, null=True)),
                ('strat_nn', models.IntegerField(default=1)),
                ('stratum', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='strata_values', to='creel_portal.Strata')),
            ],
        ),
    ]
