# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creel_portal', '0012_fr712'),
    ]

    operations = [
        migrations.AddField(
            model_name='fn112',
            name='atydur',
            field=models.FloatField(default=0, help_text='Period Duration'),
        ),
    ]
