# Generated by Django 2.2.18 on 2022-01-27 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creel_portal', '0012_prune_FN022_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fn026',
            old_name='ddlat',
            new_name='dd_lat',
        ),
        migrations.RenameField(
            model_name='fn026',
            old_name='ddlon',
            new_name='dd_lon',
        ),
    ]
