# Generated by Django 2.2.7 on 2019-11-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creel_portal', '0013_fn112_atydur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fn028',
            name='chkflag',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0, help_text='Check Flag'),
        ),
    ]
