# Generated by Django 2.2.18 on 2022-01-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creel_portal', '0013_ddlat_ddlon_to_dd_lat_dd_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fn026',
            name='area_lst',
            field=models.CharField(blank=True, help_text='Area List', max_length=20, null=True),
        ),
    ]
