# Generated by Django 2.2.18 on 2022-01-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creel_portal', '0014_fn026_area_lst_to_20'),
    ]

    operations = [
        migrations.AddField(
            model_name='fn125',
            name='tissue',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
