# Generated by Django 2.2.18 on 2022-01-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creel_portal', '0015_FN125_tissue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fn125',
            name='age',
        ),
        migrations.AddField(
            model_name='fn125',
            name='age_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fn125',
            name='comment5',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fn125',
            name='lam_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fn125',
            name='stom_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fn125',
            name='tag_flag',
            field=models.BooleanField(default=False),
        ),
    ]
