# Generated by Django 2.2.18 on 2022-02-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creel_portal', '0016_FN125_flag_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fn028',
            name='atyunit',
            field=models.IntegerField(choices=[(1, 'person'), (2, 'party')], default=1, help_text='Activity Unit'),
        ),
        migrations.AlterField(
            model_name='fn028',
            name='itvunit',
            field=models.IntegerField(choices=[(1, 'person'), (2, 'party')], default=1, help_text='Interview Unit'),
        ),
        migrations.AlterField(
            model_name='fn121',
            name='angmeth',
            field=models.IntegerField(blank=True, choices=[(1, 'Still'), (2, 'Jig'), (3, 'Drift'), (4, 'Troll'), (5, 'Down rig'), (6, 'Spin cast'), (7, 'Fly cast'), (8, 'Other/combination')], null=True),
        ),
        migrations.AlterField(
            model_name='fn121',
            name='angorig',
            field=models.IntegerField(blank=True, choices=[(1, 'Local'), (2, 'Ontario'), (3, 'Canada'), (4, 'US'), (5, 'Other')], null=True),
        ),
        migrations.AlterField(
            model_name='fn121',
            name='angvis',
            field=models.IntegerField(blank=True, choices=[(1, 'Permanent resident'), (2, 'Non-permanent resident'), (3, 'Day tripper'), (4, 'Camp-provincial park'), (5, 'Camp-commercial park'), (6, 'Camp-crown land'), (7, 'Other-paid'), (8, 'Other-non-paid')], null=True),
        ),
    ]
