# Generated by Django 2.2.18 on 2022-03-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creel_portal', '0017_add_fn121_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fn125_tag',
            name='xtaginckd',
        ),
        migrations.AlterField(
            model_name='fn125_tag',
            name='tagid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
