# Generated by Django 2.2.18 on 2022-03-30 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creel_portal', '0018_update_fn125_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='FN124',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('siz', models.PositiveIntegerField()),
                ('sizcnt', models.PositiveIntegerField()),
                ('catch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='length_tallies', to='creel_portal.FN123')),
            ],
            options={
                'ordering': ['catch', 'siz'],
                'unique_together': {('catch', 'siz')},
            },
        ),
    ]
